#!/bin/bash

# Define the input file with NBA Moneyline odds
input_file="nba_data.txt"

# Define the output file for implied probabilities
output_file="implied_prob.txt"

# Loop through the lines in the input file and calculate implied probabilities
while read line; do
  home_team=$(echo $line | cut -d',' -f1)
  home_odds=$(echo $line | cut -d',' -f2)
  away_team=$(echo $line | cut -d',' -f3)
  away_odds=$(echo $line | cut -d',' -f4)
  
  # Calculate the implied probabilities for each team
  home_prob=$(echo "scale=2; 1 / $home_odds" | bc)
  away_prob=$(echo "scale=2; 1 / $away_odds" | bc)
  
  # Write the implied probabilities to the output file
  echo "$home_team,$home_prob,$away_team,$away_prob" >> $output_file
done < $input_file

#This script reads the input file generated by data_collect_NBA.sh and calculates the implied probabilities for each NBA Moneyline market. The script then writes the implied probabilities to a file called implied_prob.txt.

# Note that this script assumes that the input file has the format:
# home_team,home_odds,away_team,away_odds
# ... and that the implied probabilities are rounded to two decimal places.
# You may need to modify the script to suit your specific needs.
